package mnj.mfg.model.services.client;

import mnj.mfg.model.services.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 18 14:44:00 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void populateShrink() {
        Object _ret = this.riInvokeExportedMethod(this,"populateShrink",null,null);
        return;
    }

    public void selectAllLines(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public double getPassFailVal(String buyer) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPassFailVal",new String [] {"java.lang.String"},new Object[] {buyer});
        return ((Double)_ret).doubleValue();
    }

    public double getTotalRollsYards(String type, String headerid,
                                     String color) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getTotalRollsYards",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {type, headerid, color});
        return ((Double)_ret).doubleValue();
    }

    public void setColorWiseWherClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setColorWiseWherClause",null,null);
        return;
    }

    public void populateShade() {
        Object _ret = this.riInvokeExportedMethod(this,"populateShade",null,null);
        return;
    }

    public Row createShadeLines() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createShadeLines",null,null);
        return (Row)_ret;
    }

    public void popuFabInsRoll() {
        Object _ret = this.riInvokeExportedMethod(this,"popuFabInsRoll",null,null);
        return;
    }

    public void popDefectCode() {
        Object _ret = this.riInvokeExportedMethod(this,"popDefectCode",null,null);
        return;
    }

    public void popuOunceRoll() {
        Object _ret = this.riInvokeExportedMethod(this,"popuOunceRoll",null,null);
        return;
    }

    public void populatePatternAloc() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populatePatternAloc",null,null);
        return;
    }

    public void setPtrnAlocRollsWhere() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPtrnAlocRollsWhere",null,null);
        return;
    }

    public void setProdShadeRolsWhereClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setProdShadeRolsWhereClause",null,null);
        return;
    }

    public void selectAllLinesFabricShade(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLinesFabricShade",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void selectAllLinesFabricRollInsp(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLinesFabricRollInsp",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void creatFabricOunceLine() {
        Object _ret =
            this.riInvokeExportedMethod(this,"creatFabricOunceLine",null,null);
        return;
    }

    public void setFabInsRollWhrCls(String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setFabInsRollWhrCls",new String [] {"java.lang.String"},new Object[] {type});
        return;
    }

    public void SelectAllLinesPatAlloc(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"SelectAllLinesPatAlloc",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void SmartCalculation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"SmartCalculation",null,null);
        return;
    }

    public void getRollSerialNo() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getRollSerialNo",null,null);
        return;
    }

    public void setPopUpWhereClauseBalance() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPopUpWhereClauseBalance",null,null);
        return;
    }

    public int RollTransfer() {
        Object _ret = this.riInvokeExportedMethod(this,"RollTransfer",null,null);
        return ((Integer)_ret).intValue();
    }

    public void popupSelectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupSelectActionListener",null,null);
        return;
    }

    public void popupDeselectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupDeselectActionListener",null,null);
        return;
    }

    public String RollTransferWhole() {
        Object _ret =
            this.riInvokeExportedMethod(this,"RollTransferWhole",null,null);
        return (String)_ret;
    }

    public void Detele_All_RecordsLines() {
        Object _ret =
            this.riInvokeExportedMethod(this,"Detele_All_RecordsLines",null,null);
        return;
    }

    public void RollTransfertoHeader() {
        Object _ret =
            this.riInvokeExportedMethod(this,"RollTransfertoHeader",null,null);
        return;
    }

    public void SelectAllRoll(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"SelectAllRoll",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void resetViewObject() {
        Object _ret =
            this.riInvokeExportedMethod(this,"resetViewObject",null,null);
        return;
    }
}
