package mnj.mfg.model.views;

import mnj.mfg.model.entities.FebricOunceLineImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 10 13:32:20 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FebricOunceLineViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        NoumberRollChecked {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getNoumberRollChecked();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setNoumberRollChecked((String)value);
            }
        }
        ,
        RequireFabricOunce {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getRequireFabricOunce();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setRequireFabricOunce((String)value);
            }
        }
        ,
        BwOunce {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getBwOunce();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setBwOunce((Number)value);
            }
        }
        ,
        AwOunce {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAwOunce();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAwOunce((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ProdLId {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getProdLId();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        Variation {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getVariation();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setVariation((Number)value);
            }
        }
        ,
        VariationPrcnt {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getVariationPrcnt();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setVariationPrcnt((Number)value);
            }
        }
        ,
        Inspection {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getInspection();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setInspection((String)value);
            }
        }
        ,
        InsDate {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getInsDate();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setInsDate((Date)value);
            }
        }
        ,
        FebricOunceDetailView {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getFebricOunceDetailView();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InspectionVO1 {
            public Object get(FebricOunceLineViewRowImpl obj) {
                return obj.getInspectionVO1();
            }

            public void put(FebricOunceLineViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(FebricOunceLineViewRowImpl object);

        public abstract void put(FebricOunceLineViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int NOUMBERROLLCHECKED = AttributesEnum.NoumberRollChecked.index();
    public static final int REQUIREFABRICOUNCE = AttributesEnum.RequireFabricOunce.index();
    public static final int BWOUNCE = AttributesEnum.BwOunce.index();
    public static final int AWOUNCE = AttributesEnum.AwOunce.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int VARIATION = AttributesEnum.Variation.index();
    public static final int VARIATIONPRCNT = AttributesEnum.VariationPrcnt.index();
    public static final int INSPECTION = AttributesEnum.Inspection.index();
    public static final int INSDATE = AttributesEnum.InsDate.index();
    public static final int FEBRICOUNCEDETAILVIEW = AttributesEnum.FebricOunceDetailView.index();
    public static final int INSPECTIONVO1 = AttributesEnum.InspectionVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FebricOunceLineViewRowImpl() {
    }

    /**
     * Gets FebricOunceLine entity object.
     * @return the FebricOunceLine
     */
    public FebricOunceLineImpl getFebricOunceLine() {
        return (FebricOunceLineImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for NOUMBER_ROLL_CHECKED using the alias name NoumberRollChecked.
     * @return the NOUMBER_ROLL_CHECKED
     */
    public String getNoumberRollChecked() {
        return (String) getAttributeInternal(NOUMBERROLLCHECKED);
    }

    /**
     * Sets <code>value</code> as attribute value for NOUMBER_ROLL_CHECKED using the alias name NoumberRollChecked.
     * @param value value to set the NOUMBER_ROLL_CHECKED
     */
    public void setNoumberRollChecked(String value) {
        setAttributeInternal(NOUMBERROLLCHECKED, value);
    }

    /**
     * Gets the attribute value for REQUIRE_FABRIC_OUNCE using the alias name RequireFabricOunce.
     * @return the REQUIRE_FABRIC_OUNCE
     */
    public String getRequireFabricOunce() {
        return (String) getAttributeInternal(REQUIREFABRICOUNCE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUIRE_FABRIC_OUNCE using the alias name RequireFabricOunce.
     * @param value value to set the REQUIRE_FABRIC_OUNCE
     */
    public void setRequireFabricOunce(String value) {
        setAttributeInternal(REQUIREFABRICOUNCE, value);
    }

    /**
     * Gets the attribute value for BW_OUNCE using the alias name BwOunce.
     * @return the BW_OUNCE
     */
    public Number getBwOunce() {
        return (Number) getAttributeInternal(BWOUNCE);
    }

    /**
     * Sets <code>value</code> as attribute value for BW_OUNCE using the alias name BwOunce.
     * @param value value to set the BW_OUNCE
     */
    public void setBwOunce(Number value) {
        setAttributeInternal(BWOUNCE, value);
    }

    /**
     * Gets the attribute value for AW_OUNCE using the alias name AwOunce.
     * @return the AW_OUNCE
     */
    public Number getAwOunce() {
        return (Number) getAttributeInternal(AWOUNCE);
    }

    /**
     * Sets <code>value</code> as attribute value for AW_OUNCE using the alias name AwOunce.
     * @param value value to set the AW_OUNCE
     */
    public void setAwOunce(Number value) {
        setAttributeInternal(AWOUNCE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PROD_L_ID using the alias name ProdLId.
     * @return the PROD_L_ID
     */
    public Number getProdLId() {
        return (Number) getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_L_ID using the alias name ProdLId.
     * @param value value to set the PROD_L_ID
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for VARIATION using the alias name Variation.
     * @return the VARIATION
     */
    public Number getVariation() {
        return (Number) getAttributeInternal(VARIATION);
    }

    /**
     * Sets <code>value</code> as attribute value for VARIATION using the alias name Variation.
     * @param value value to set the VARIATION
     */
    public void setVariation(Number value) {
        setAttributeInternal(VARIATION, value);
    }

    /**
     * Gets the attribute value for VARIATION_PRCNT using the alias name VariationPrcnt.
     * @return the VARIATION_PRCNT
     */
    public Number getVariationPrcnt() {
        return (Number) getAttributeInternal(VARIATIONPRCNT);
    }

    /**
     * Sets <code>value</code> as attribute value for VARIATION_PRCNT using the alias name VariationPrcnt.
     * @param value value to set the VARIATION_PRCNT
     */
    public void setVariationPrcnt(Number value) {
        setAttributeInternal(VARIATIONPRCNT, value);
    }

    /**
     * Gets the attribute value for INSPECTION using the alias name Inspection.
     * @return the INSPECTION
     */
    public String getInspection() {
        return (String) getAttributeInternal(INSPECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION using the alias name Inspection.
     * @param value value to set the INSPECTION
     */
    public void setInspection(String value) {
        setAttributeInternal(INSPECTION, value);
    }

    /**
     * Gets the attribute value for INS_DATE using the alias name InsDate.
     * @return the INS_DATE
     */
    public Date getInsDate() {
        return (Date) getAttributeInternal(INSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INS_DATE using the alias name InsDate.
     * @param value value to set the INS_DATE
     */
    public void setInsDate(Date value) {
        setAttributeInternal(INSDATE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FebricOunceDetailView.
     */
    public RowIterator getFebricOunceDetailView() {
        return (RowIterator)getAttributeInternal(FEBRICOUNCEDETAILVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InspectionVO1.
     */
    public RowSet getInspectionVO1() {
        return (RowSet)getAttributeInternal(INSPECTIONVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
