package mnj.mfg.model.lovviews;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 29 10:58:29 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ColorFabRollInvVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        FinishGoodColor {
            public Object get(ColorFabRollInvVORowImpl obj) {
                return obj.getFinishGoodColor();
            }

            public void put(ColorFabRollInvVORowImpl obj, Object value) {
                obj.setFinishGoodColor((String)value);
            }
        }
        ,
        Color {
            public Object get(ColorFabRollInvVORowImpl obj) {
                return obj.getColor();
            }

            public void put(ColorFabRollInvVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ColorFabRollInvVORowImpl object);

        public abstract void put(ColorFabRollInvVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FINISHGOODCOLOR = AttributesEnum.FinishGoodColor.index();
    public static final int COLOR = AttributesEnum.Color.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ColorFabRollInvVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FinishGoodColor.
     * @return the FinishGoodColor
     */
    public String getFinishGoodColor() {
        return (String) getAttributeInternal(FINISHGOODCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FinishGoodColor.
     * @param value value to set the  FinishGoodColor
     */
    public void setFinishGoodColor(String value) {
        setAttributeInternal(FINISHGOODCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
