package mnj.mfg.model.lovviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 29 10:58:30 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ColorFabRollInvVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ColorFabRollInvVOImpl() {
    }

    /**
     * Returns the bind variable value for p_recpt_no.
     * @return bind variable value for p_recpt_no
     */
    public String getp_recpt_no() {
        return (String)getNamedWhereClauseParam("p_recpt_no");
    }

    /**
     * Sets <code>value</code> for bind variable p_recpt_no.
     * @param value value to bind as p_recpt_no
     */
    public void setp_recpt_no(String value) {
        setNamedWhereClauseParam("p_recpt_no", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
