package mnj.mfg.model.lovviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 16 11:32:54 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FabOuncePopUpVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FabOuncePopUpVOImpl() {
    }
}
