package mnj.mfg.model.lovviews;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 15:21:54 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvStyleFabShrinkVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Style {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        ArticleNo {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getArticleNo();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setArticleNo((String)value);
            }
        }
        ,
        Composition {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getComposition();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setComposition((String)value);
            }
        }
        ,
        Construction {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getConstruction();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setConstruction((String)value);
            }
        }
        ,
        RawColor {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getRawColor();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setRawColor((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        FabOunce {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getFabOunce();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setFabOunce((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(InvStyleFabShrinkVORowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(InvStyleFabShrinkVORowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InvStyleFabShrinkVORowImpl object);

        public abstract void put(InvStyleFabShrinkVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int ARTICLENO = AttributesEnum.ArticleNo.index();
    public static final int COMPOSITION = AttributesEnum.Composition.index();
    public static final int CONSTRUCTION = AttributesEnum.Construction.index();
    public static final int RAWCOLOR = AttributesEnum.RawColor.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int FABOUNCE = AttributesEnum.FabOunce.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvStyleFabShrinkVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArticleNo.
     * @return the ArticleNo
     */
    public String getArticleNo() {
        return (String) getAttributeInternal(ARTICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArticleNo.
     * @param value value to set the  ArticleNo
     */
    public void setArticleNo(String value) {
        setAttributeInternal(ARTICLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Composition.
     * @return the Composition
     */
    public String getComposition() {
        return (String) getAttributeInternal(COMPOSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Composition.
     * @param value value to set the  Composition
     */
    public void setComposition(String value) {
        setAttributeInternal(COMPOSITION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Construction.
     * @return the Construction
     */
    public String getConstruction() {
        return (String) getAttributeInternal(CONSTRUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Construction.
     * @param value value to set the  Construction
     */
    public void setConstruction(String value) {
        setAttributeInternal(CONSTRUCTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RawColor.
     * @return the RawColor
     */
    public String getRawColor() {
        return (String) getAttributeInternal(RAWCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RawColor.
     * @param value value to set the  RawColor
     */
    public void setRawColor(String value) {
        setAttributeInternal(RAWCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FabOunce.
     * @return the FabOunce
     */
    public String getFabOunce() {
        return (String) getAttributeInternal(FABOUNCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FabOunce.
     * @param value value to set the  FabOunce
     */
    public void setFabOunce(String value) {
        setAttributeInternal(FABOUNCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
