package mnj.mfg.model.lovviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 13:52:43 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewBalancePopUpImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewBalancePopUpImpl() {
    }
}
