package mnj.mfg.model.lovviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 10 12:59:47 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RollNoLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RollNoLOVImpl() {
    }
}
