package mnj.mfg.model.lovviews;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 20 14:33:42 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransferRollHeaderVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TransferRollHeaderVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ORG_ID.
     * @return bind variable value for P_ORG_ID
     */
    public String getP_ORG_ID() {
        return (String)getNamedWhereClauseParam("P_ORG_ID");
    }
}
