package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 10 12:13:06 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FebricOunceLineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getHeaderId();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getLineId();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        NoumberRollChecked {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getNoumberRollChecked();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setNoumberRollChecked((String)value);
            }
        }
        ,
        RequireFabricOunce {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getRequireFabricOunce();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setRequireFabricOunce((String)value);
            }
        }
        ,
        BwOunce {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getBwOunce();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setBwOunce((Number)value);
            }
        }
        ,
        AwOunce {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAwOunce();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAwOunce((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getRemarks();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute1();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute3();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute4();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute5();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute6();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute7();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute8();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute9();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute10();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute11();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute12();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute13();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute14();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getAttribute15();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getOrgId();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ProdLId {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getProdLId();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        Variation {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getVariation();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setVariation((Number)value);
            }
        }
        ,
        VariationPrcnt {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getVariationPrcnt();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setVariationPrcnt((Number)value);
            }
        }
        ,
        Inspection {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getInspection();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setInspection((String)value);
            }
        }
        ,
        InsDate {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getInsDate();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setInsDate((Date)value);
            }
        }
        ,
        FebricOunceDetail {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getFebricOunceDetail();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgFabinsProdLEO {
            public Object get(FebricOunceLineImpl obj) {
                return obj.getMnjMfgFabinsProdLEO();
            }

            public void put(FebricOunceLineImpl obj, Object value) {
                obj.setMnjMfgFabinsProdLEO((MnjMfgFabinsProdLEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(FebricOunceLineImpl object);

        public abstract void put(FebricOunceLineImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    //public static final int MNJMFGFABRICINSTESTH = AttributesEnum.MnjMfgFabricInsTestH.index();


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int NOUMBERROLLCHECKED = AttributesEnum.NoumberRollChecked.index();
    public static final int REQUIREFABRICOUNCE = AttributesEnum.RequireFabricOunce.index();
    public static final int BWOUNCE = AttributesEnum.BwOunce.index();
    public static final int AWOUNCE = AttributesEnum.AwOunce.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int VARIATION = AttributesEnum.Variation.index();
    public static final int VARIATIONPRCNT = AttributesEnum.VariationPrcnt.index();
    public static final int INSPECTION = AttributesEnum.Inspection.index();
    public static final int INSDATE = AttributesEnum.InsDate.index();
    public static final int FEBRICOUNCEDETAIL = AttributesEnum.FebricOunceDetail.index();
    public static final int MNJMFGFABINSPRODLEO = AttributesEnum.MnjMfgFabinsProdLEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FebricOunceLineImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.FebricOunceLine");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for NoumberRollChecked, using the alias name NoumberRollChecked.
     * @return the NoumberRollChecked
     */
    public String getNoumberRollChecked() {
        return (String)getAttributeInternal(NOUMBERROLLCHECKED);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoumberRollChecked.
     * @param value value to set the NoumberRollChecked
     */
    public void setNoumberRollChecked(String value) {
        setAttributeInternal(NOUMBERROLLCHECKED, value);
    }

    /**
     * Gets the attribute value for RequireFabricOunce, using the alias name RequireFabricOunce.
     * @return the RequireFabricOunce
     */
    public String getRequireFabricOunce() {
        return (String)getAttributeInternal(REQUIREFABRICOUNCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequireFabricOunce.
     * @param value value to set the RequireFabricOunce
     */
    public void setRequireFabricOunce(String value) {
        setAttributeInternal(REQUIREFABRICOUNCE, value);
    }

    /**
     * Gets the attribute value for BwOunce, using the alias name BwOunce.
     * @return the BwOunce
     */
    public Number getBwOunce() {
        return (Number)getAttributeInternal(BWOUNCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BwOunce.
     * @param value value to set the BwOunce
     */
    public void setBwOunce(Number value) {
        setAttributeInternal(BWOUNCE, value);
    }

    /**
     * Gets the attribute value for AwOunce, using the alias name AwOunce.
     * @return the AwOunce
     */
    public Number getAwOunce() {
        return (Number)getAttributeInternal(AWOUNCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwOunce.
     * @param value value to set the AwOunce
     */
    public void setAwOunce(Number value) {
        setAttributeInternal(AWOUNCE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ProdLId, using the alias name ProdLId.
     * @return the ProdLId
     */
    public Number getProdLId() {
        return (Number)getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLId.
     * @param value value to set the ProdLId
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for Variation, using the alias name Variation.
     * @return the Variation
     */
    public Number getVariation() {
        return (Number)getAttributeInternal(VARIATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Variation.
     * @param value value to set the Variation
     */
    public void setVariation(Number value) {
        setAttributeInternal(VARIATION, value);
    }

    /**
     * Gets the attribute value for VariationPrcnt, using the alias name VariationPrcnt.
     * @return the VariationPrcnt
     */
    public Number getVariationPrcnt() {
        return (Number)getAttributeInternal(VARIATIONPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for VariationPrcnt.
     * @param value value to set the VariationPrcnt
     */
    public void setVariationPrcnt(Number value) {
        setAttributeInternal(VARIATIONPRCNT, value);
    }

    /**
     * Gets the attribute value for Inspection, using the alias name Inspection.
     * @return the Inspection
     */
    public String getInspection() {
        return (String)getAttributeInternal(INSPECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inspection.
     * @param value value to set the Inspection
     */
    public void setInspection(String value) {
        setAttributeInternal(INSPECTION, value);
    }

    /**
     * Gets the attribute value for InsDate, using the alias name InsDate.
     * @return the InsDate
     */
    public Date getInsDate() {
        return (Date)getAttributeInternal(INSDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsDate.
     * @param value value to set the InsDate
     */
    public void setInsDate(Date value) {
        setAttributeInternal(INSDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgFabricInsTestHImpl.
     */
//    public MnjMfgFabricInsTestHImpl getMnjMfgFabricInsTestH() {
//        return (MnjMfgFabricInsTestHImpl)getAttributeInternal(MNJMFGFABRICINSTESTH);
//    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabricInsTestHImpl.
//     */
//    public void setMnjMfgFabricInsTestH(MnjMfgFabricInsTestHImpl value) {
//        setAttributeInternal(MNJMFGFABRICINSTESTH, value);
//    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getFebricOunceDetail() {
        return (RowIterator)getAttributeInternal(FEBRICOUNCEDETAIL);
    }


    /**
     * @return the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public MnjMfgFabinsProdLEOImpl getMnjMfgFabinsProdLEO() {
        return (MnjMfgFabinsProdLEOImpl)getAttributeInternal(MNJMFGFABINSPRODLEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public void setMnjMfgFabinsProdLEO(MnjMfgFabinsProdLEOImpl value) {
        setAttributeInternal(MNJMFGFABINSPRODLEO, value);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_FABRI_COUNCE_LINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setLineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

     /**
      * Add locking logic here.
      */
     //    public void lock() {
     //        super.lock();
     //    }
      public void lock() {
         try {
             super.lock();
         } catch (oracle.jbo.RowInconsistentException e) {
             if (e.getErrorCode().equals("25014")) {
                 super.lock();
             } else
                 throw e;
         }
     }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
