package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 17 20:50:28 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgFabricInsTestLImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        RollNo {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRollNo();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRollNo((String)value);
            }
        }
        ,
        RollLength {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRollLength();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRollLength((Number)value);
            }
        }
        ,
        RollWidth {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRollWidth();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRollWidth((Number)value);
            }
        }
        ,
        AwLength {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getAwLength();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setAwLength((Number)value);
            }
        }
        ,
        ShrinkLength {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getShrinkLength();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setShrinkLength((Number)value);
            }
        }
        ,
        ShrinkPrcLength {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getShrinkPrcLength();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setShrinkPrcLength((Number)value);
            }
        }
        ,
        AwWidth {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getAwWidth();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setAwWidth((Number)value);
            }
        }
        ,
        ShrinkWidth {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getShrinkWidth();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setShrinkWidth((Number)value);
            }
        }
        ,
        ShrinkPrcWidth {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getShrinkPrcWidth();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setShrinkPrcWidth((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LineType {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getLineType();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        Shade {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getShade();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setShade((String)value);
            }
        }
        ,
        ProdLId {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getProdLId();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        AlocYard {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getAlocYard();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setAlocYard((Number)value);
            }
        }
        ,
        CutWidth {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getCutWidth();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setCutWidth((Number)value);
            }
        }
        ,
        RollLength2 {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRollLength2();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRollLength2((Number)value);
            }
        }
        ,
        AlocInch {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getAlocInch();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setAlocInch((Number)value);
            }
        }
        ,
        BlncYards {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getBlncYards();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setBlncYards((Number)value);
            }
        }
        ,
        BlncInch {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getBlncInch();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setBlncInch((Number)value);
            }
        }
        ,
        RawItemId {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getRawItemId();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setRawItemId((Number)value);
            }
        }
        ,
        SuppRollNo {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getSuppRollNo();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setSuppRollNo((String)value);
            }
        }
        ,
        MnjMfgFabinsProdLEO {
            public Object get(MnjMfgFabricInsTestLImpl obj) {
                return obj.getMnjMfgFabinsProdLEO();
            }

            public void put(MnjMfgFabricInsTestLImpl obj, Object value) {
                obj.setMnjMfgFabinsProdLEO((MnjMfgFabinsProdLEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgFabricInsTestLImpl object);

        public abstract void put(MnjMfgFabricInsTestLImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ROLLNO = AttributesEnum.RollNo.index();
    public static final int ROLLLENGTH = AttributesEnum.RollLength.index();
    public static final int ROLLWIDTH = AttributesEnum.RollWidth.index();
    public static final int AWLENGTH = AttributesEnum.AwLength.index();
    public static final int SHRINKLENGTH = AttributesEnum.ShrinkLength.index();
    public static final int SHRINKPRCLENGTH = AttributesEnum.ShrinkPrcLength.index();
    public static final int AWWIDTH = AttributesEnum.AwWidth.index();
    public static final int SHRINKWIDTH = AttributesEnum.ShrinkWidth.index();
    public static final int SHRINKPRCWIDTH = AttributesEnum.ShrinkPrcWidth.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int SHADE = AttributesEnum.Shade.index();
    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int ALOCYARD = AttributesEnum.AlocYard.index();
    public static final int CUTWIDTH = AttributesEnum.CutWidth.index();
    public static final int ROLLLENGTH2 = AttributesEnum.RollLength2.index();
    public static final int ALOCINCH = AttributesEnum.AlocInch.index();
    public static final int BLNCYARDS = AttributesEnum.BlncYards.index();
    public static final int BLNCINCH = AttributesEnum.BlncInch.index();
    public static final int RAWITEMID = AttributesEnum.RawItemId.index();
    public static final int SUPPROLLNO = AttributesEnum.SuppRollNo.index();
    public static final int MNJMFGFABINSPRODLEO = AttributesEnum.MnjMfgFabinsProdLEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgFabricInsTestLImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgFabricInsTestL");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for RollNo, using the alias name RollNo.
     * @return the RollNo
     */
    public String getRollNo() {
        return (String)getAttributeInternal(ROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollNo.
     * @param value value to set the RollNo
     */
    public void setRollNo(String value) {
        setAttributeInternal(ROLLNO, value);
    }

    /**
     * Gets the attribute value for RollLength, using the alias name RollLength.
     * @return the RollLength
     */
    public Number getRollLength() {
        return (Number)getAttributeInternal(ROLLLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollLength.
     * @param value value to set the RollLength
     */
    public void setRollLength(Number value) {
        setAttributeInternal(ROLLLENGTH, value);
    }

    /**
     * Gets the attribute value for RollWidth, using the alias name RollWidth.
     * @return the RollWidth
     */
    public Number getRollWidth() {
        return (Number)getAttributeInternal(ROLLWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollWidth.
     * @param value value to set the RollWidth
     */
    public void setRollWidth(Number value) {
        setAttributeInternal(ROLLWIDTH, value);
    }

    /**
     * Gets the attribute value for AwLength, using the alias name AwLength.
     * @return the AwLength
     */
    public Number getAwLength() {
        return (Number)getAttributeInternal(AWLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwLength.
     * @param value value to set the AwLength
     */
    public void setAwLength(Number value) {
        setAttributeInternal(AWLENGTH, value);
    }

    /**
     * Gets the attribute value for ShrinkLength, using the alias name ShrinkLength.
     * @return the ShrinkLength
     */
    public Number getShrinkLength() {
        return (Number)getAttributeInternal(SHRINKLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkLength.
     * @param value value to set the ShrinkLength
     */
    public void setShrinkLength(Number value) {
        setAttributeInternal(SHRINKLENGTH, value);
    }

    /**
     * Gets the attribute value for ShrinkPrcLength, using the alias name ShrinkPrcLength.
     * @return the ShrinkPrcLength
     */
    public Number getShrinkPrcLength() {
        return (Number)getAttributeInternal(SHRINKPRCLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkPrcLength.
     * @param value value to set the ShrinkPrcLength
     */
    public void setShrinkPrcLength(Number value) {
        setAttributeInternal(SHRINKPRCLENGTH, value);
    }

    /**
     * Gets the attribute value for AwWidth, using the alias name AwWidth.
     * @return the AwWidth
     */
    public Number getAwWidth() {
        return (Number)getAttributeInternal(AWWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwWidth.
     * @param value value to set the AwWidth
     */
    public void setAwWidth(Number value) {
        setAttributeInternal(AWWIDTH, value);
    }

    /**
     * Gets the attribute value for ShrinkWidth, using the alias name ShrinkWidth.
     * @return the ShrinkWidth
     */
    public Number getShrinkWidth() {
        return (Number)getAttributeInternal(SHRINKWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkWidth.
     * @param value value to set the ShrinkWidth
     */
    public void setShrinkWidth(Number value) {
        setAttributeInternal(SHRINKWIDTH, value);
    }

    /**
     * Gets the attribute value for ShrinkPrcWidth, using the alias name ShrinkPrcWidth.
     * @return the ShrinkPrcWidth
     */
    public Number getShrinkPrcWidth() {
        return (Number)getAttributeInternal(SHRINKPRCWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkPrcWidth.
     * @param value value to set the ShrinkPrcWidth
     */
    public void setShrinkPrcWidth(Number value) {
        setAttributeInternal(SHRINKPRCWIDTH, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LineType, using the alias name LineType.
     * @return the LineType
     */
    public String getLineType() {
        return (String)getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineType.
     * @param value value to set the LineType
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for Shade, using the alias name Shade.
     * @return the Shade
     */
    public String getShade() {
        return (String)getAttributeInternal(SHADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shade.
     * @param value value to set the Shade
     */
    public void setShade(String value) {
        setAttributeInternal(SHADE, value);
    }

    /**
     * Gets the attribute value for ProdLId, using the alias name ProdLId.
     * @return the ProdLId
     */
    public Number getProdLId() {
        return (Number)getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLId.
     * @param value value to set the ProdLId
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for AlocYard, using the alias name AlocYard.
     * @return the AlocYard
     */
    public Number getAlocYard() {
        return (Number)getAttributeInternal(ALOCYARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocYard.
     * @param value value to set the AlocYard
     */
    public void setAlocYard(Number value) {
        setAttributeInternal(ALOCYARD, value);
    }

    /**
     * Gets the attribute value for CutWidth, using the alias name CutWidth.
     * @return the CutWidth
     */
    public Number getCutWidth() {
        return (Number)getAttributeInternal(CUTWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutWidth.
     * @param value value to set the CutWidth
     */
    public void setCutWidth(Number value) {
        setAttributeInternal(CUTWIDTH, value);
    }

    /**
     * Gets the attribute value for RollLength2, using the alias name RollLength2.
     * @return the RollLength2
     */
    public Number getRollLength2() {
        return (Number)getAttributeInternal(ROLLLENGTH2);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollLength2.
     * @param value value to set the RollLength2
     */
    public void setRollLength2(Number value) {
        setAttributeInternal(ROLLLENGTH2, value);
    }

    /**
     * Gets the attribute value for AlocInch, using the alias name AlocInch.
     * @return the AlocInch
     */
    public Number getAlocInch() {
        return (Number)getAttributeInternal(ALOCINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlocInch.
     * @param value value to set the AlocInch
     */
    public void setAlocInch(Number value) {
        setAttributeInternal(ALOCINCH, value);
    }

    /**
     * Gets the attribute value for BlncYards, using the alias name BlncYards.
     * @return the BlncYards
     */
    public Number getBlncYards() {
        return (Number)getAttributeInternal(BLNCYARDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncYards.
     * @param value value to set the BlncYards
     */
    public void setBlncYards(Number value) {
        setAttributeInternal(BLNCYARDS, value);
    }

    /**
     * Gets the attribute value for BlncInch, using the alias name BlncInch.
     * @return the BlncInch
     */
    public Number getBlncInch() {
        return (Number)getAttributeInternal(BLNCINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncInch.
     * @param value value to set the BlncInch
     */
    public void setBlncInch(Number value) {
        setAttributeInternal(BLNCINCH, value);
    }

    /**
     * Gets the attribute value for RawItemId, using the alias name RawItemId.
     * @return the RawItemId
     */
    public Number getRawItemId() {
        return (Number)getAttributeInternal(RAWITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RawItemId.
     * @param value value to set the RawItemId
     */
    public void setRawItemId(Number value) {
        setAttributeInternal(RAWITEMID, value);
    }

    /**
     * Gets the attribute value for SuppRollNo, using the alias name SuppRollNo.
     * @return the SuppRollNo
     */
    public String getSuppRollNo() {
        return (String)getAttributeInternal(SUPPROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppRollNo.
     * @param value value to set the SuppRollNo
     */
    public void setSuppRollNo(String value) {
        setAttributeInternal(SUPPROLLNO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public MnjMfgFabinsProdLEOImpl getMnjMfgFabinsProdLEO() {
        return (MnjMfgFabinsProdLEOImpl)getAttributeInternal(MNJMFGFABINSPRODLEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public void setMnjMfgFabinsProdLEO(MnjMfgFabinsProdLEOImpl value) {
        setAttributeInternal(MNJMFGFABINSPRODLEO, value);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_MFG_FABRIC_INS_TEST_L_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setLineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

     /**
      * Add locking logic here.
      */
     //    public void lock() {
     //        super.lock();
     //    }
      public void lock() {
         try {
             super.lock();
         } catch (oracle.jbo.RowInconsistentException e) {
             if (e.getErrorCode().equals("25014")) {
                 super.lock();
             } else
                 throw e;
         }
     }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
