package mnj.mfg.model.entities;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 22 12:31:22 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgFabinsProdLEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_FABINS_PROD_L_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        System.out.println("Recent Created LineId: " + sVal);
        setProdLId(sVal);
    }
    
    /**
     * Add locking logic here.
     */
    //    public void lock() {
    //        super.lock();
    //    }
     public void lock() {
        try {
            super.lock();
        } catch (oracle.jbo.RowInconsistentException e) {
            if (e.getErrorCode().equals("25014")) {
                super.lock();
            } else
                throw e;
        }
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    @Override
    protected void addListBindingsForAttribute(java.util.List list,
                                               java.util.List list2,
                                               String string,
                                               ArrayList arrayList,
                                               ArrayList arrayList2) {
        super.addListBindingsForAttribute(list, list2, string, arrayList, arrayList2);
    }
/*
    @Override
    public boolean isAttributeUpdateable(int i) {
        return  getSystemId()!= null ? false : super.isAttributeUpdateable(i);
    }

*/
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProdLId {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getProdLId();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        FabCons {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getFabCons();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setFabCons((String)value);
            }
        }
        ,
        FabComp {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getFabComp();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setFabComp((String)value);
            }
        }
        ,
        TotalAlocRolls {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getTotalAlocRolls();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setTotalAlocRolls((Number)value);
            }
        }
        ,
        TotalAlocYrds {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getTotalAlocYrds();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setTotalAlocYrds((Number)value);
            }
        }
        ,
        BlncRolls {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getBlncRolls();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setBlncRolls((Number)value);
            }
        }
        ,
        BlncYrds {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getBlncYrds();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setBlncYrds((Number)value);
            }
        }
        ,
        DjCutWidth {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getDjCutWidth();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setDjCutWidth((String)value);
            }
        }
        ,
        Inspection {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getInspection();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setInspection((String)value);
            }
        }
        ,
        TotalAlocInch {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getTotalAlocInch();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setTotalAlocInch((Number)value);
            }
        }
        ,
        BlncInch {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getBlncInch();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setBlncInch((Number)value);
            }
        }
        ,
        RawColor {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getRawColor();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setRawColor((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        FabOunce {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getFabOunce();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setFabOunce((String)value);
            }
        }
        ,
        FinishedGarmentsColor {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getFinishedGarmentsColor();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setFinishedGarmentsColor((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        Lot {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getLot();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setLot((String)value);
            }
        }
        ,
        Wash {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getWash();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        ArticleNo {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getArticleNo();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setArticleNo((String)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        MnjMfgFabricInsTestH {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjMfgFabricInsTestH();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setMnjMfgFabricInsTestH((MnjMfgFabricInsTestHImpl)value);
            }
        }
        ,
        MnjMfgFabricInsTestL {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjMfgFabricInsTestL();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgFabricInsTestShdL {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjMfgFabricInsTestShdL();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FebricOunceLine {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getFebricOunceLine();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgFabinsFirstDEO {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjMfgFabinsFirstDEO();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgFabinsPtrnalocL {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjMfgFabinsPtrnalocL();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RollTransferHistoryEO {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getRollTransferHistoryEO();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjSkewMovementEO {
            public Object get(MnjMfgFabinsProdLEOImpl obj) {
                return obj.getMnjSkewMovementEO();
            }

            public void put(MnjMfgFabinsProdLEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgFabinsProdLEOImpl object);

        public abstract void put(MnjMfgFabinsProdLEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int FABCONS = AttributesEnum.FabCons.index();
    public static final int FABCOMP = AttributesEnum.FabComp.index();
    public static final int TOTALALOCROLLS = AttributesEnum.TotalAlocRolls.index();
    public static final int TOTALALOCYRDS = AttributesEnum.TotalAlocYrds.index();
    public static final int BLNCROLLS = AttributesEnum.BlncRolls.index();
    public static final int BLNCYRDS = AttributesEnum.BlncYrds.index();
    public static final int DJCUTWIDTH = AttributesEnum.DjCutWidth.index();
    public static final int INSPECTION = AttributesEnum.Inspection.index();
    public static final int TOTALALOCINCH = AttributesEnum.TotalAlocInch.index();
    public static final int BLNCINCH = AttributesEnum.BlncInch.index();
    public static final int RAWCOLOR = AttributesEnum.RawColor.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FABOUNCE = AttributesEnum.FabOunce.index();
    public static final int FINISHEDGARMENTSCOLOR = AttributesEnum.FinishedGarmentsColor.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LOT = AttributesEnum.Lot.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int ARTICLENO = AttributesEnum.ArticleNo.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int MNJMFGFABRICINSTESTH = AttributesEnum.MnjMfgFabricInsTestH.index();
    public static final int MNJMFGFABRICINSTESTL = AttributesEnum.MnjMfgFabricInsTestL.index();
    public static final int MNJMFGFABRICINSTESTSHDL = AttributesEnum.MnjMfgFabricInsTestShdL.index();
    public static final int FEBRICOUNCELINE = AttributesEnum.FebricOunceLine.index();
    public static final int MNJMFGFABINSFIRSTDEO = AttributesEnum.MnjMfgFabinsFirstDEO.index();
    public static final int MNJMFGFABINSPTRNALOCL = AttributesEnum.MnjMfgFabinsPtrnalocL.index();
    public static final int ROLLTRANSFERHISTORYEO = AttributesEnum.RollTransferHistoryEO.index();
    public static final int MNJSKEWMOVEMENTEO = AttributesEnum.MnjSkewMovementEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgFabinsProdLEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgFabinsProdLEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ProdLId, using the alias name ProdLId.
     * @return the ProdLId
     */
    public Number getProdLId() {
        return (Number)getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLId.
     * @param value value to set the ProdLId
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }


    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }


    /**
     * Gets the attribute value for FabCons, using the alias name FabCons.
     * @return the FabCons
     */
    public String getFabCons() {
        return (String)getAttributeInternal(FABCONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabCons.
     * @param value value to set the FabCons
     */
    public void setFabCons(String value) {
        setAttributeInternal(FABCONS, value);
    }

    /**
     * Gets the attribute value for FabComp, using the alias name FabComp.
     * @return the FabComp
     */
    public String getFabComp() {
        return (String)getAttributeInternal(FABCOMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabComp.
     * @param value value to set the FabComp
     */
    public void setFabComp(String value) {
        setAttributeInternal(FABCOMP, value);
    }

    /**
     * Gets the attribute value for TotalAlocRolls, using the alias name TotalAlocRolls.
     * @return the TotalAlocRolls
     */
    public Number getTotalAlocRolls() {
        return (Number)getAttributeInternal(TOTALALOCROLLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalAlocRolls.
     * @param value value to set the TotalAlocRolls
     */
    public void setTotalAlocRolls(Number value) {
        setAttributeInternal(TOTALALOCROLLS, value);
    }

    /**
     * Gets the attribute value for TotalAlocYrds, using the alias name TotalAlocYrds.
     * @return the TotalAlocYrds
     */
    public Number getTotalAlocYrds() {
        return (Number)getAttributeInternal(TOTALALOCYRDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalAlocYrds.
     * @param value value to set the TotalAlocYrds
     */
    public void setTotalAlocYrds(Number value) {
        setAttributeInternal(TOTALALOCYRDS, value);
    }

    /**
     * Gets the attribute value for BlncRolls, using the alias name BlncRolls.
     * @return the BlncRolls
     */
    public Number getBlncRolls() {
        return (Number)getAttributeInternal(BLNCROLLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncRolls.
     * @param value value to set the BlncRolls
     */
    public void setBlncRolls(Number value) {
        setAttributeInternal(BLNCROLLS, value);
    }

    /**
     * Gets the attribute value for BlncYrds, using the alias name BlncYrds.
     * @return the BlncYrds
     */
    public Number getBlncYrds() {
        return (Number)getAttributeInternal(BLNCYRDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncYrds.
     * @param value value to set the BlncYrds
     */
    public void setBlncYrds(Number value) {
        setAttributeInternal(BLNCYRDS, value);
    }

    /**
     * Gets the attribute value for DjCutWidth, using the alias name DjCutWidth.
     * @return the DjCutWidth
     */
    public String getDjCutWidth() {
        return (String)getAttributeInternal(DJCUTWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DjCutWidth.
     * @param value value to set the DjCutWidth
     */
    public void setDjCutWidth(String value) {
        setAttributeInternal(DJCUTWIDTH, value);
    }

    /**
     * Gets the attribute value for Inspection, using the alias name Inspection.
     * @return the Inspection
     */
    public String getInspection() {
        return (String)getAttributeInternal(INSPECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inspection.
     * @param value value to set the Inspection
     */
    public void setInspection(String value) {
        setAttributeInternal(INSPECTION, value);
    }

    /**
     * Gets the attribute value for TotalAlocInch, using the alias name TotalAlocInch.
     * @return the TotalAlocInch
     */
    public Number getTotalAlocInch() {
        return (Number)getAttributeInternal(TOTALALOCINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalAlocInch.
     * @param value value to set the TotalAlocInch
     */
    public void setTotalAlocInch(Number value) {
        setAttributeInternal(TOTALALOCINCH, value);
    }

    /**
     * Gets the attribute value for BlncInch, using the alias name BlncInch.
     * @return the BlncInch
     */
    public Number getBlncInch() {
        return (Number)getAttributeInternal(BLNCINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncInch.
     * @param value value to set the BlncInch
     */
    public void setBlncInch(Number value) {
        setAttributeInternal(BLNCINCH, value);
    }

    /**
     * Gets the attribute value for RawColor, using the alias name RawColor.
     * @return the RawColor
     */
    public String getRawColor() {
        return (String)getAttributeInternal(RAWCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for RawColor.
     * @param value value to set the RawColor
     */
    public void setRawColor(String value) {
        setAttributeInternal(RAWCOLOR, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for FabOunce, using the alias name FabOunce.
     * @return the FabOunce
     */
    public String getFabOunce() {
        return (String)getAttributeInternal(FABOUNCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabOunce.
     * @param value value to set the FabOunce
     */
    public void setFabOunce(String value) {
        setAttributeInternal(FABOUNCE, value);
    }

    /**
     * Gets the attribute value for FinishedGarmentsColor, using the alias name FinishedGarmentsColor.
     * @return the FinishedGarmentsColor
     */
    public String getFinishedGarmentsColor() {
        return (String)getAttributeInternal(FINISHEDGARMENTSCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinishedGarmentsColor.
     * @param value value to set the FinishedGarmentsColor
     */
    public void setFinishedGarmentsColor(String value) {
        setAttributeInternal(FINISHEDGARMENTSCOLOR, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for Lot, using the alias name Lot.
     * @return the Lot
     */
    public String getLot() {
        return (String)getAttributeInternal(LOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lot.
     * @param value value to set the Lot
     */
    public void setLot(String value) {
        setAttributeInternal(LOT, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for ArticleNo, using the alias name ArticleNo.
     * @return the ArticleNo
     */
    public String getArticleNo() {
        return (String)getAttributeInternal(ARTICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArticleNo.
     * @param value value to set the ArticleNo
     */
    public void setArticleNo(String value) {
        setAttributeInternal(ARTICLENO, value);
    }


    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgFabricInsTestHImpl.
     */
    public MnjMfgFabricInsTestHImpl getMnjMfgFabricInsTestH() {
        return (MnjMfgFabricInsTestHImpl)getAttributeInternal(MNJMFGFABRICINSTESTH);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabricInsTestHImpl.
     */
    public void setMnjMfgFabricInsTestH(MnjMfgFabricInsTestHImpl value) {
        setAttributeInternal(MNJMFGFABRICINSTESTH, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgFabricInsTestL() {
        return (RowIterator)getAttributeInternal(MNJMFGFABRICINSTESTL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgFabricInsTestShdL() {
        return (RowIterator)getAttributeInternal(MNJMFGFABRICINSTESTSHDL);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getFebricOunceLine() {
        return (RowIterator)getAttributeInternal(FEBRICOUNCELINE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgFabinsFirstDEO() {
        return (RowIterator)getAttributeInternal(MNJMFGFABINSFIRSTDEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgFabinsPtrnalocL() {
        return (RowIterator)getAttributeInternal(MNJMFGFABINSPTRNALOCL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRollTransferHistoryEO() {
        return (RowIterator)getAttributeInternal(ROLLTRANSFERHISTORYEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjSkewMovementEO() {
        return (RowIterator)getAttributeInternal(MNJSKEWMOVEMENTEO);
    }

    /**
     * @param prodLId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number prodLId) {
        return new Key(new Object[]{prodLId});
    }


}
