package mnj.mfg.model.entities;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 07 14:09:22 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjSkewMovementDEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjSkewMovementDEOCollImpl() {
    }
}
