package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 06 10:57:53 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjSkewMovementEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SkewLineId {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getSkewLineId();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setSkewLineId((Number)value);
            }
        }
        ,
        ProdLId {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getProdLId();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        RollNo {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getRollNo();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setRollNo((String)value);
            }
        }
        ,
        Ac {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getAc();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setAc((Number)value);
            }
        }
        ,
        Bd {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getBd();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setBd((Number)value);
            }
        }
        ,
        AcMinusBd {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getAcMinusBd();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setAcMinusBd((Number)value);
            }
        }
        ,
        AcAddBd {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getAcAddBd();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setAcAddBd((Number)value);
            }
        }
        ,
        Result {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getResult();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setResult((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Passfail {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getPassfail();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setPassfail((String)value);
            }
        }
        ,
        SkewInspection {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getSkewInspection();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setSkewInspection((String)value);
            }
        }
        ,
        SkewInspectionDate {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getSkewInspectionDate();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setSkewInspectionDate((Date)value);
            }
        }
        ,
        MnjMfgFabinsProdLEO {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getMnjMfgFabinsProdLEO();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setMnjMfgFabinsProdLEO((MnjMfgFabinsProdLEOImpl)value);
            }
        }
        ,
        MnjSkewMovementDEO {
            public Object get(MnjSkewMovementEOImpl obj) {
                return obj.getMnjSkewMovementDEO();
            }

            public void put(MnjSkewMovementEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjSkewMovementEOImpl object);

        public abstract void put(MnjSkewMovementEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SKEWLINEID = AttributesEnum.SkewLineId.index();
    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int ROLLNO = AttributesEnum.RollNo.index();
    public static final int AC = AttributesEnum.Ac.index();
    public static final int BD = AttributesEnum.Bd.index();
    public static final int ACMINUSBD = AttributesEnum.AcMinusBd.index();
    public static final int ACADDBD = AttributesEnum.AcAddBd.index();
    public static final int RESULT = AttributesEnum.Result.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int PASSFAIL = AttributesEnum.Passfail.index();
    public static final int SKEWINSPECTION = AttributesEnum.SkewInspection.index();
    public static final int SKEWINSPECTIONDATE = AttributesEnum.SkewInspectionDate.index();
    public static final int MNJMFGFABINSPRODLEO = AttributesEnum.MnjMfgFabinsProdLEO.index();
    public static final int MNJSKEWMOVEMENTDEO = AttributesEnum.MnjSkewMovementDEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjSkewMovementEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjSkewMovementEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for SkewLineId, using the alias name SkewLineId.
     * @return the SkewLineId
     */
    public Number getSkewLineId() {
        return (Number)getAttributeInternal(SKEWLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SkewLineId.
     * @param value value to set the SkewLineId
     */
    public void setSkewLineId(Number value) {
        setAttributeInternal(SKEWLINEID, value);
    }

    /**
     * Gets the attribute value for ProdLId, using the alias name ProdLId.
     * @return the ProdLId
     */
    public Number getProdLId() {
        return (Number)getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLId.
     * @param value value to set the ProdLId
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for RollNo, using the alias name RollNo.
     * @return the RollNo
     */
    public String getRollNo() {
        return (String)getAttributeInternal(ROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollNo.
     * @param value value to set the RollNo
     */
    public void setRollNo(String value) {
        setAttributeInternal(ROLLNO, value);
    }

    /**
     * Gets the attribute value for Ac, using the alias name Ac.
     * @return the Ac
     */
    public Number getAc() {
        return (Number)getAttributeInternal(AC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ac.
     * @param value value to set the Ac
     */
    public void setAc(Number value) {
        setAttributeInternal(AC, value);
    }

    /**
     * Gets the attribute value for Bd, using the alias name Bd.
     * @return the Bd
     */
    public Number getBd() {
        return (Number)getAttributeInternal(BD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bd.
     * @param value value to set the Bd
     */
    public void setBd(Number value) {
        setAttributeInternal(BD, value);
    }

    /**
     * Gets the attribute value for AcMinusBd, using the alias name AcMinusBd.
     * @return the AcMinusBd
     */
    public Number getAcMinusBd() {
        return (Number)getAttributeInternal(ACMINUSBD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AcMinusBd.
     * @param value value to set the AcMinusBd
     */
    public void setAcMinusBd(Number value) {
        setAttributeInternal(ACMINUSBD, value);
    }

    /**
     * Gets the attribute value for AcAddBd, using the alias name AcAddBd.
     * @return the AcAddBd
     */
    public Number getAcAddBd() {
        return (Number)getAttributeInternal(ACADDBD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AcAddBd.
     * @param value value to set the AcAddBd
     */
    public void setAcAddBd(Number value) {
        setAttributeInternal(ACADDBD, value);
    }

    /**
     * Gets the attribute value for Result, using the alias name Result.
     * @return the Result
     */
    public Number getResult() {
        return (Number)getAttributeInternal(RESULT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Result.
     * @param value value to set the Result
     */
    public void setResult(Number value) {
        setAttributeInternal(RESULT, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Passfail, using the alias name Passfail.
     * @return the Passfail
     */
    public String getPassfail() {
        return (String)getAttributeInternal(PASSFAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Passfail.
     * @param value value to set the Passfail
     */
    public void setPassfail(String value) {
        setAttributeInternal(PASSFAIL, value);
    }

    /**
     * Gets the attribute value for SkewInspection, using the alias name SkewInspection.
     * @return the SkewInspection
     */
    public String getSkewInspection() {
        return (String)getAttributeInternal(SKEWINSPECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for SkewInspection.
     * @param value value to set the SkewInspection
     */
    public void setSkewInspection(String value) {
        setAttributeInternal(SKEWINSPECTION, value);
    }

    /**
     * Gets the attribute value for SkewInspectionDate, using the alias name SkewInspectionDate.
     * @return the SkewInspectionDate
     */
    public Date getSkewInspectionDate() {
        return (Date)getAttributeInternal(SKEWINSPECTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SkewInspectionDate.
     * @param value value to set the SkewInspectionDate
     */
    public void setSkewInspectionDate(Date value) {
        setAttributeInternal(SKEWINSPECTIONDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public MnjMfgFabinsProdLEOImpl getMnjMfgFabinsProdLEO() {
        return (MnjMfgFabinsProdLEOImpl)getAttributeInternal(MNJMFGFABINSPRODLEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public void setMnjMfgFabinsProdLEO(MnjMfgFabinsProdLEOImpl value) {
        setAttributeInternal(MNJMFGFABINSPRODLEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjSkewMovementDEO() {
        return (RowIterator)getAttributeInternal(MNJSKEWMOVEMENTDEO);
    }


    /**
     * @param skewLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number skewLineId) {
        return new Key(new Object[]{skewLineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_SKEW_MOVEMENT_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSkewLineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

     /**
      * Add locking logic here.
      */
     //    public void lock() {
     //        super.lock();
     //    }
      public void lock() {
         try {
             super.lock();
         } catch (oracle.jbo.RowInconsistentException e) {
             if (e.getErrorCode().equals("25014")) {
                 super.lock();
             } else
                 throw e;
         }
     }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
