package mnj.mfg.model.entities;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 06 10:04:27 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjSkewMovementEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjSkewMovementEOCollImpl() {
    }
}
