package mnj.mfg.model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 21 12:40:04 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RollTransferHistoryEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HistoryId {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getHistoryId();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setHistoryId((Number)value);
            }
        }
        ,
        ProdLId {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getProdLId();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setProdLId((Number)value);
            }
        }
        ,
        FactoryRollNo {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getFactoryRollNo();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setFactoryRollNo((String)value);
            }
        }
        ,
        SupplierRollNo {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getSupplierRollNo();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setSupplierRollNo((String)value);
            }
        }
        ,
        TransferToDoc {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getTransferToDoc();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setTransferToDoc((String)value);
            }
        }
        ,
        MnjMfgFabinsProdLEO {
            public Object get(RollTransferHistoryEOImpl obj) {
                return obj.getMnjMfgFabinsProdLEO();
            }

            public void put(RollTransferHistoryEOImpl obj, Object value) {
                obj.setMnjMfgFabinsProdLEO((MnjMfgFabinsProdLEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RollTransferHistoryEOImpl object);

        public abstract void put(RollTransferHistoryEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int HISTORYID = AttributesEnum.HistoryId.index();
    public static final int PRODLID = AttributesEnum.ProdLId.index();
    public static final int FACTORYROLLNO = AttributesEnum.FactoryRollNo.index();
    public static final int SUPPLIERROLLNO = AttributesEnum.SupplierRollNo.index();
    public static final int TRANSFERTODOC = AttributesEnum.TransferToDoc.index();
    public static final int MNJMFGFABINSPRODLEO = AttributesEnum.MnjMfgFabinsProdLEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RollTransferHistoryEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.RollTransferHistoryEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HistoryId, using the alias name HistoryId.
     * @return the HistoryId
     */
    public Number getHistoryId() {
        return (Number)getAttributeInternal(HISTORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HistoryId.
     * @param value value to set the HistoryId
     */
    public void setHistoryId(Number value) {
        setAttributeInternal(HISTORYID, value);
    }

    /**
     * Gets the attribute value for ProdLId, using the alias name ProdLId.
     * @return the ProdLId
     */
    public Number getProdLId() {
        return (Number)getAttributeInternal(PRODLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLId.
     * @param value value to set the ProdLId
     */
    public void setProdLId(Number value) {
        setAttributeInternal(PRODLID, value);
    }

    /**
     * Gets the attribute value for FactoryRollNo, using the alias name FactoryRollNo.
     * @return the FactoryRollNo
     */
    public String getFactoryRollNo() {
        return (String)getAttributeInternal(FACTORYROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FactoryRollNo.
     * @param value value to set the FactoryRollNo
     */
    public void setFactoryRollNo(String value) {
        setAttributeInternal(FACTORYROLLNO, value);
    }

    /**
     * Gets the attribute value for SupplierRollNo, using the alias name SupplierRollNo.
     * @return the SupplierRollNo
     */
    public String getSupplierRollNo() {
        return (String)getAttributeInternal(SUPPLIERROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierRollNo.
     * @param value value to set the SupplierRollNo
     */
    public void setSupplierRollNo(String value) {
        setAttributeInternal(SUPPLIERROLLNO, value);
    }

    /**
     * Gets the attribute value for TransferToDoc, using the alias name TransferToDoc.
     * @return the TransferToDoc
     */
    public String getTransferToDoc() {
        return (String)getAttributeInternal(TRANSFERTODOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransferToDoc.
     * @param value value to set the TransferToDoc
     */
    public void setTransferToDoc(String value) {
        setAttributeInternal(TRANSFERTODOC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public MnjMfgFabinsProdLEOImpl getMnjMfgFabinsProdLEO() {
        return (MnjMfgFabinsProdLEOImpl)getAttributeInternal(MNJMFGFABINSPRODLEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFabinsProdLEOImpl.
     */
    public void setMnjMfgFabinsProdLEO(MnjMfgFabinsProdLEOImpl value) {
        setAttributeInternal(MNJMFGFABINSPRODLEO, value);
    }

    /**
     * @param historyId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number historyId) {
        return new Key(new Object[]{historyId});
    }


}
