package mnj.mfg.model.lovviews.mdssys;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 13:10:58 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BalancePopUpVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BalancePopUpVOImpl() {
    }
}
