package mnj.mfg.model.lovviews.mdssys;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 13:10:56 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BalancePopUpVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BalanceYards {
            public Object get(BalancePopUpVORowImpl obj) {
                return obj.getBalanceYards();
            }

            public void put(BalancePopUpVORowImpl obj, Object value) {
                obj.setBalanceYards((Number)value);
            }
        }
        ,
        BalanceInch {
            public Object get(BalancePopUpVORowImpl obj) {
                return obj.getBalanceInch();
            }

            public void put(BalancePopUpVORowImpl obj, Object value) {
                obj.setBalanceInch((Number)value);
            }
        }
        ,
        BalanceRolls {
            public Object get(BalancePopUpVORowImpl obj) {
                return obj.getBalanceRolls();
            }

            public void put(BalancePopUpVORowImpl obj, Object value) {
                obj.setBalanceRolls((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(BalancePopUpVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(BalancePopUpVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        RawColor {
            public Object get(BalancePopUpVORowImpl obj) {
                return obj.getRawColor();
            }

            public void put(BalancePopUpVORowImpl obj, Object value) {
                obj.setRawColor((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BalancePopUpVORowImpl object);

        public abstract void put(BalancePopUpVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BALANCEYARDS = AttributesEnum.BalanceYards.index();
    public static final int BALANCEINCH = AttributesEnum.BalanceInch.index();
    public static final int BALANCEROLLS = AttributesEnum.BalanceRolls.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int RAWCOLOR = AttributesEnum.RawColor.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BalancePopUpVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceYards.
     * @return the BalanceYards
     */
    public Number getBalanceYards() {
        return (Number) getAttributeInternal(BALANCEYARDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceYards.
     * @param value value to set the  BalanceYards
     */
    public void setBalanceYards(Number value) {
        setAttributeInternal(BALANCEYARDS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceInch.
     * @return the BalanceInch
     */
    public Number getBalanceInch() {
        return (Number) getAttributeInternal(BALANCEINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceInch.
     * @param value value to set the  BalanceInch
     */
    public void setBalanceInch(Number value) {
        setAttributeInternal(BALANCEINCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceRolls.
     * @return the BalanceRolls
     */
    public Number getBalanceRolls() {
        return (Number) getAttributeInternal(BALANCEROLLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceRolls.
     * @param value value to set the  BalanceRolls
     */
    public void setBalanceRolls(Number value) {
        setAttributeInternal(BALANCEROLLS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RawColor.
     * @return the RawColor
     */
    public String getRawColor() {
        return (String) getAttributeInternal(RAWCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RawColor.
     * @param value value to set the  RawColor
     */
    public void setRawColor(String value) {
        setAttributeInternal(RAWCOLOR, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
